# Generated by Django 2.2 on 2020-10-20 22:59

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='bookingdate',
            name='checkout_date_constraint',
        ),
        migrations.AddConstraint(
            model_name='bookingdate',
            constraint=models.CheckConstraint(check=models.Q(checkout__gt=django.db.models.functions.datetime.Now()), name='checkout_date_constraint'),
        ),
        migrations.AddConstraint(
            model_name='bookingdate',
            constraint=models.UniqueConstraint(fields=('checkin', 'checkout', 'property'), name='unique_date_constraint'),
        ),
        migrations.AddField(
            model_name='images',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Property'),
        ),
    ]
