# Generated by Django 2.2 on 2020-10-20 23:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20201020_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Property')),
            ],
            options={
                'verbose_name': 'Booking Period',
                'verbose_name_plural': 'Booking Periods',
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='active',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='BookingDate',
        ),
        migrations.AddConstraint(
            model_name='bookingperiod',
            constraint=models.CheckConstraint(check=models.Q(finish__gt=django.db.models.functions.datetime.Now()), name='finish_date_constraint'),
        ),
        migrations.AddConstraint(
            model_name='bookingperiod',
            constraint=models.UniqueConstraint(fields=('start', 'finish', 'property'), name='unique_date_constraint'),
        ),
    ]
