# Generated by Django 3.1.2 on 2020-10-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_property_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(default='img/image-not-found.png', upload_to='img/'),
        ),
    ]
