# Generated by Django 3.1.2 on 2020-10-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20201027_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(default='img/image-not-found.png', upload_to='booking/static/img/properties'),
        ),
    ]
