# Generated by Django 3.1.2 on 2020-10-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20201027_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='booking/static/img/properties'),
        ),
    ]
