# Generated by Django 3.1.2 on 2020-10-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20201028_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
